#!/usr/bin/env bash

#PBS -N depth_coverage_NJ_PE
#PBS -l nodes=1:ppn=40 #1 of node requested; 20 processors in total
#PBS -l walltime=48:00:00 # 48 hours walltime
#PBS -l mem=150gb #150 Gb memory in total
#PBS -m abe
#PBS -M MohammedHisham.Shaikh@ugent.be
#PBS -o /data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics/logs/${PBS_JOBNAME}_output.log  
#PBS -e /data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics/logs/${PBS_JOBNAME}_error.log   



#Making sure I am on the rigth cluster
module swap cluster/doduo

# Unset OMP_PROC_BIND
unset OMP_PROC_BIND



# AIM: Depth coverage for NJ_PE_cross_assembly

. ~/vo_vliz.sh
. .bashrc

# Defining directories
HOME_DIR="/data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics"
OUTPUT_DIR="$HOME_DIR/working/5_depth_coverage/1_NJ_PE"
MAPPING_DIR="$HOME_DIR/working/4_read_mapping/1_NJ_PE/mapping"
DEPTH_FILE="$OUTPUT_DIR/NJ_PE_depth.txt"

mkdir -p $OUTPUT_DIR
cd $OUTPUT_DIR


mamba activate metabat2

jgi_summarize_bam_contig_depths --outputDepth $DEPTH_FILE $MAPPING_DIR/*_mapped_reads_sorted.bam

mamba deactivate