#!/usr/bin/env bash

#PBS -N bowtie2_mapping_quant_NJ_PE_clustered
#PBS -l nodes=1:ppn=40 #1 of node requested; 20 processors in total
#PBS -l walltime=48:00:00 # 48 hours walltime
#PBS -l mem=150gb #150 Gb memory in total
#PBS -m abe
#PBS -M MohammedHisham.Shaikh@ugent.be
#PBS -o /data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics/logs/${PBS_JOBNAME}_output.log  
#PBS -e /data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics/logs/${PBS_JOBNAME}_error.log   



#Making sure I am on the rigth cluster
module swap cluster/doduo

# Unset OMP_PROC_BIND
unset OMP_PROC_BIND



# AIM: Read mapping and quantifictaion for NJ_PE clustered cross_assembly

# Read mapping is required to get depth coverage necessary for binning and also for read quanitfication

. ~/vo_vliz.sh
. .bashrc

# Defining directories
HOME_DIR="/data/gent/vo/001/gvo00125/vsc44392/Projects/North_Sea_Viral_Metagenomics"
OUTPUT_DIR="$HOME_DIR/working/5_read_mapping/1_NJ_PE"
TRIMMED_READS_DIR="$HOME_DIR/working/1_read_qc_trimming/1_fastp_trim_qc"
CLUSTERED_ASSEMBLY="$HOME_DIR/working/3_clustering/NJ_PE_cd_hit/NJ_PE_clustered_contigs.fa"
SAMPLE_LIST="$HOME_DIR/data/sample_overview/NJ_PE_sample_list.csv"
INDEX_DIR="$OUTPUT_DIR/index"
MAPPING_DIR="$OUTPUT_DIR/mapping"
COMBINED_QUANT_DIR="$OUTPUT_DIR/combined_quant"

mkdir -p $OUTPUT_DIR $INDEX_DIR $MAPPING_DIR $COMBINED_QUANT_DIR
cd $OUTPUT_DIR


mamba activate bowtie2

# Building Bowtie2 index for the assembled contigs
bowtie2-build $CLUSTERED_ASSEMBLY $INDEX_DIR/NJ_PE_index

# Creating combined quantification file
COMBINED_QUANT="$COMBINED_QUANT_DIR/combined_read_counts_NJ_PE.txt"

echo -e "Sample\tContig\tContig_Length\tMapped_Reads\tUnmapped_Reads" > $COMBINED_QUANT

# Looping through samples
for sample in $(cat $SAMPLE_LIST); do
    echo "Processing sample: $sample"
    
    # Defining file paths for paired-end reads
    R1="$TRIMMED_READS_DIR/${sample}_R1_paired.fastq.gz"
    R2="$TRIMMED_READS_DIR/${sample}_R2_paired.fastq.gz"
    BAM="$MAPPING_DIR/${sample}_mapped_reads_sorted.bam"
    QUANT="$MAPPING_DIR/${sample}_read_counts.txt"

    # Mapping reads to contigs and generate BAM file
    bowtie2 -x $INDEX_DIR/NJ_PE_index -1 $R1 -2 $R2 --threads 40 | samtools view -bS - | samtools sort -o $BAM

    # Indexing BAM file 
    samtools index $BAM

    # Quantifing reads mapped to contigs
    samtools idxstats $BAM > $QUANT

    # Adding sample name and aggregate into combined file
    awk -v sample="$sample" 'BEGIN {FS="\t"} {print sample"\t"$1"\t"$2"\t"$3"\t"$4}' $QUANT >> $COMBINED_QUANT

done 

echo "Quantification for all samples. Combined results saved in $COMBINED_QUANT"

mamba deactivate